/**
 * Common Kerala Temple Poojas and Offerings Catalog
 * Sourced from:
 * 1. Chocherikunnu Sree Subramanya Swami Temple (keralapazhanitemple.com/offerings)
 * 2. Sree Uma Maheswara Swami Temple (templeofquilon.org/vazhipadu.html)
 */

export const POOJA_CATEGORIES = [
  'All',
  'Pushpanjali & Archana',
  'Homam',
  'Abhishekam',
  'Nivedyam & Payasam',
  'Special & Deity Pooja',
  'Mala & Vilakku',
  'Sanskaras & Life Events',
]

export const COMMON_POOJAS = [
  /* ── 1. Pushpanjali & Archana ── */
  {
    name: 'Swayamwara Pushpanjali',
    amount: 20,
    category: 'Pushpanjali & Archana',
    description: 'Special pushpanjali for removal of marriage obstacles and relationship harmony.',
    source: 'Both',
  },
  {
    name: 'Bhagya Sooktha Pushpanjali',
    amount: 20,
    category: 'Pushpanjali & Archana',
    description: 'Vedic hymn chanting for prosperity, luck, and fortune.',
    source: 'Both',
  },
  {
    name: 'Saaraswatha Pushpanjali',
    amount: 20,
    category: 'Pushpanjali & Archana',
    description: 'For academic success, intellect, memory power, and wisdom.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Vidhya Sooktha Pushpanjali',
    amount: 20,
    category: 'Pushpanjali & Archana',
    description: 'Prayer for learning, knowledge, and educational excellence.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Aikyamathya Pushpanjali',
    amount: 20,
    category: 'Pushpanjali & Archana',
    description: 'For family harmony, unity, peace, and resolving disputes.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Mrithyunjaya Pushpanjali',
    amount: 20,
    category: 'Pushpanjali & Archana',
    description: 'For good health, longevity, and warding off ill health.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Shathru Samhara Pushpanjali',
    amount: 20,
    category: 'Pushpanjali & Archana',
    description: 'To overcome negative energies, evil eyes, and adversaries.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Raktha Pushpanjali',
    amount: 20,
    category: 'Pushpanjali & Archana',
    description: 'Traditional red flower offering to Devi for protection and courage.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Swasthi Manthra Pushpanjali',
    amount: 20,
    category: 'Pushpanjali & Archana',
    description: 'Offering with auspicious Vedic Swasthi Suktam mantras.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Durga Manthra Pushpanjali',
    amount: 20,
    category: 'Pushpanjali & Archana',
    description: 'Offerings to Durga Devi for overcoming life hurdles.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Purusha Sooktha Pushpanjali',
    amount: 20,
    category: 'Pushpanjali & Archana',
    description: 'Vedic chanting of Purusha Suktam for spiritual elevation.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Sthree Sooktha Pushpanjali',
    amount: 20,
    category: 'Pushpanjali & Archana',
    description: 'Auspicious mantra offering for well-being of women.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Kumara Sooktha Pushpanjali',
    amount: 50,
    category: 'Pushpanjali & Archana',
    description: 'Dedicated to Lord Muruga / Subrahmanya for courage and victory.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Aayur Sooktha Pushpanjali',
    amount: 50,
    category: 'Pushpanjali & Archana',
    description: 'Prayer for longevity, vitality, and curing illness.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Subramanya Kavacha Pushpanjali',
    amount: 50,
    category: 'Pushpanjali & Archana',
    description: 'Chanting of protective Kavacha mantras for Lord Subramanya.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Subramanya Sthothra Pushpanjali',
    amount: 50,
    category: 'Pushpanjali & Archana',
    description: 'Stotra dedication for Lord Murugan blessings.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Samvada Sooktha Pushpanjali',
    amount: 20,
    category: 'Pushpanjali & Archana',
    description: 'For cordial mutual relations and peaceful communication.',
    source: 'Both',
  },
  {
    name: 'Santhanagopala Manthra Pushpanjali',
    amount: 25,
    category: 'Pushpanjali & Archana',
    description: 'Special prayer for progeny and blessings for expecting parents.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Saraswathy Manthra Pushpanjali',
    amount: 20,
    category: 'Pushpanjali & Archana',
    description: 'Dedicated to Goddess Saraswathi for arts, music, and education.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Ashtothara Archana',
    amount: 50,
    category: 'Pushpanjali & Archana',
    description: '108 divine names archana with sacred offerings.',
    source: 'Both',
  },
  {
    name: 'Sahasranama Archana',
    amount: 100,
    category: 'Pushpanjali & Archana',
    description: '1000 names archana for profound divine grace and peace.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Kumkumarchana',
    amount: 25,
    category: 'Pushpanjali & Archana',
    description: 'Kumkum offering archana to Devi for Soubhagya.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Thrisathy Archana',
    amount: 30,
    category: 'Pushpanjali & Archana',
    description: '300 holy names archana ritual.',
    source: 'templeofquilon.org',
  },

  /* ── 2. Homams ── */
  {
    name: 'Ganapathi Homam',
    amount: 501,
    category: 'Homam',
    description: 'Sacred fire ritual to Lord Ganesha for auspicious beginnings and obstacles removal.',
    source: 'Both',
  },
  {
    name: 'Ashtadravya Ganapathy Homam',
    amount: 501,
    category: 'Homam',
    description: 'Elaborate Ganapathy Homam using 8 sacred herbal ingredients.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Bhagya Sooktha Ganapathy Homam',
    amount: 501,
    category: 'Homam',
    description: 'Ganapathy Homam combined with Bhagya Sukta for financial prosperity.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Mrithyunjaya Homam',
    amount: 1001,
    category: 'Homam',
    description: 'Powerful fire ritual to Lord Shiva for healing, health recovery, and long life.',
    source: 'Both',
  },
  {
    name: 'Maha Mrithyunjaya Homam',
    amount: 1001,
    category: 'Homam',
    description: 'Grand Mrithyunjaya Homam performed with Vedic rituals for serious health ailments.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Samoha Mrithyunjaya Homam',
    amount: 251,
    category: 'Homam',
    description: 'Community prayer homam performed on first Saturdays of Malayalam months.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Karuka Homam',
    amount: 251,
    category: 'Homam',
    description: 'Homam offering tender Karuka grass to Ganesha for children health and welfare.',
    source: 'Both',
  },
  {
    name: 'Thila Homam',
    amount: 251,
    category: 'Homam',
    description: 'Sesame seeds fire offering to mitigate planetary doshas and ancestral peace.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Bhasneshi Homam',
    amount: 1001,
    category: 'Homam',
    description: 'Special homam ritual for fulfillment of deep desires and family peace.',
    source: 'keralapazhanitemple.com',
  },

  /* ── 3. Abhishekams ── */
  {
    name: 'Jaladhara',
    amount: 501,
    category: 'Abhishekam',
    description: 'Continuous cooling holy water bath (108 pots) for Lord Shiva.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Neyyabhishekam (Ghee)',
    amount: 251,
    category: 'Abhishekam',
    description: 'Pure cow ghee abhishekam to the deity for spiritual cleansing.',
    source: 'Both',
  },
  {
    name: 'Paal Abhishekam (Milk)',
    amount: 51,
    category: 'Abhishekam',
    description: 'Fresh cow milk sacred bath for the deity.',
    source: 'Both',
  },
  {
    name: 'Oru Kudam Paalabhishekam',
    amount: 500,
    category: 'Abhishekam',
    description: 'Full pot milk abhishekam for special occasions.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Panchamritha Abhishekam',
    amount: 151,
    category: 'Abhishekam',
    description: 'Bath with 5 divine nectars: milk, curd, honey, ghee, and banana.',
    source: 'Both',
  },
  {
    name: 'Elaneer Abhishekam (Tender Coconut)',
    amount: 101,
    category: 'Abhishekam',
    description: 'Abhishekam with pure tender coconut water.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Bhasmabhishekam (Vibhoothi)',
    amount: 101,
    category: 'Abhishekam',
    description: 'Sacred ash holy bath for Shiva and Subrahmanya.',
    source: 'Both',
  },
  {
    name: 'Kalabhabhishekam (Sandalwood Paste)',
    amount: 201,
    category: 'Abhishekam',
    description: 'Precious sandalwood paste offering covering the deity.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Panineer Abhishekam (Rose Water)',
    amount: 101,
    category: 'Abhishekam',
    description: 'Fragrant rose water sacred offering.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Shangabhishekam (Conch Abhishekam)',
    amount: 51,
    category: 'Abhishekam',
    description: 'Auspicious holy water poured through sacred conch shell.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Maharudhra Abhishekam',
    amount: 2500,
    category: 'Abhishekam',
    description: 'Grand Vedic Rudrabhishekam by high priests.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Shadabhishekam',
    amount: 1500,
    category: 'Abhishekam',
    description: 'Sixfold divine ablution ceremony for the presiding deity.',
    source: 'keralapazhanitemple.com',
  },

  /* ── 4. Nivedyams & Payasam ── */
  {
    name: 'Paal Payasam',
    amount: 60,
    category: 'Nivedyam & Payasam',
    description: 'Traditional Kerala milk pudding offered to the deity and distributed as prasadam.',
    source: 'Both',
  },
  {
    name: 'Sharkara Payasam',
    amount: 50,
    category: 'Nivedyam & Payasam',
    description: 'Rich jaggery and coconut milk payasam nivedyam.',
    source: 'Both',
  },
  {
    name: 'Aravana Payasam',
    amount: 80,
    category: 'Nivedyam & Payasam',
    description: 'Thick jaggery, ghee, and rice sweet offering popular in Kerala temples.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Meni Payasam',
    amount: 100,
    category: 'Nivedyam & Payasam',
    description: 'Exquisite multi-ingredient temple pudding offering.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Unniyappam (Ottappam)',
    amount: 201,
    category: 'Nivedyam & Payasam',
    description: 'Crispy fried jaggery and banana rice dumplings for Ganesha/Muruga.',
    source: 'Both',
  },
  {
    name: 'Aval Nivedyam',
    amount: 100,
    category: 'Nivedyam & Payasam',
    description: 'Flaked rice seasoned with jaggery, grated coconut, and cardamom.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Thrimadhuram',
    amount: 100,
    category: 'Nivedyam & Payasam',
    description: 'Sacred trio of honey, banana, and sugar/ghee offering.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Panakam',
    amount: 250,
    category: 'Nivedyam & Payasam',
    description: 'Cooling jaggery, ginger, and cardamom sacred beverage.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Vellari Nivedyam',
    amount: 50,
    category: 'Nivedyam & Payasam',
    description: 'Traditional cucumber cooling nivedyam offering.',
    source: 'keralapazhanitemple.com',
  },

  /* ── 5. Special & Deity Pooja ── */
  {
    name: 'Uma Maheshwara Pooja',
    amount: 251,
    category: 'Special & Deity Pooja',
    description: 'Dedicated to Shiva and Parvathi for marital happiness and prosperity.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Ganapathi Pooja',
    amount: 151,
    category: 'Special & Deity Pooja',
    description: 'Special archana and pooja offering for Lord Ganapathy.',
    source: 'Both',
  },
  {
    name: 'Shivanu Pooja',
    amount: 151,
    category: 'Special & Deity Pooja',
    description: 'Direct pooja and deeparadhana dedicated to Lord Shiva.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Devikku Pooja',
    amount: 151,
    category: 'Special & Deity Pooja',
    description: 'Devi pooja for grace, inner strength, and family protection.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Ayyappanu Pooja',
    amount: 151,
    category: 'Special & Deity Pooja',
    description: 'Pooja for Lord Ayyappa with neyyappam / elluthiri offering.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Sreeramanu Pooja',
    amount: 151,
    category: 'Special & Deity Pooja',
    description: 'Pooja to Lord Rama for righteousness and victory.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Hanumanu Pooja',
    amount: 151,
    category: 'Special & Deity Pooja',
    description: 'Pooja to Lord Hanuman for strength, confidence, and protection.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Subrahmania Pooja',
    amount: 151,
    category: 'Special & Deity Pooja',
    description: 'Special pooja to Lord Muruga / Karthikeya.',
    source: 'Both',
  },
  {
    name: 'Bhagavathi Seva',
    amount: 501,
    category: 'Special & Deity Pooja',
    description: 'Evening tantric padmam pooja to Goddess Bhagavathi.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Udayasthamana Pooja',
    amount: 5001,
    category: 'Special & Deity Pooja',
    description: 'All-day poojas from temple sunrise opening to sunset deeparadhana.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Thrikala Pooja',
    amount: 750,
    category: 'Special & Deity Pooja',
    description: 'Pooja performed at three sandhyas: dawn, noon, and dusk.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Iswarya Pooja',
    amount: 151,
    category: 'Special & Deity Pooja',
    description: 'Aishwarya prayer for prosperity and home happiness.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Rahukala Pooja',
    amount: 151,
    category: 'Special & Deity Pooja',
    description: 'Pooja during Rahu Kalam (Fridays) to mitigate Rahu dosham.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Janmanakshathra (Birthday) Pooja',
    amount: 301,
    category: 'Special & Deity Pooja',
    description: 'Dedicated birthday pooja based on devotee birth star.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Shaniswara Pooja',
    amount: 301,
    category: 'Special & Deity Pooja',
    description: 'Saturdays special pooja to pacify Saturn / Shani dosha.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Vyazham (Guru) Pooja',
    amount: 301,
    category: 'Special & Deity Pooja',
    description: 'Thursday pooja to Jupiter / Brihaspati for wisdom and career.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Budhanu Pooja',
    amount: 301,
    category: 'Special & Deity Pooja',
    description: 'Wednesday pooja to Mercury for education and commerce.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Shukranu Pooja',
    amount: 301,
    category: 'Special & Deity Pooja',
    description: 'Friday pooja to Venus for luxury, fine arts, and matrimonial bliss.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Divasa Pooja',
    amount: 500,
    category: 'Special & Deity Pooja',
    description: 'Full day pooja sponsorship in devotee name.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Visheshal Pooja',
    amount: 1500,
    category: 'Special & Deity Pooja',
    description: 'Special tantric festival or anniversary pooja.',
    source: 'keralapazhanitemple.com',
  },

  /* ── 6. Mala & Vilakku ── */
  {
    name: 'Vadamala',
    amount: 301,
    category: 'Mala & Vilakku',
    description: 'Garland of fried vada offerings for Hanuman / Maadan Thampuran.',
    source: 'Both',
  },
  {
    name: 'Vettilamala',
    amount: 101,
    category: 'Mala & Vilakku',
    description: 'Betel leaf sacred garland offering.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Karukamala',
    amount: 50,
    category: 'Mala & Vilakku',
    description: 'Fresh holy Karuka grass garland for Lord Ganapathy.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Chuttu Vilakku',
    amount: 1000,
    category: 'Mala & Vilakku',
    description: 'Lighting all oil lamps surrounding the inner temple sanctum.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Mun Vilakku / Pin Vilakku',
    amount: 20,
    category: 'Mala & Vilakku',
    description: 'Lighting front and back oil lamps facing the deity.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Ayyappaswamikku Neeranjanam',
    amount: 100,
    category: 'Mala & Vilakku',
    description: 'Cracked coconut shell with sesame oil lamp for Lord Ayyappa.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Ellu Thiri',
    amount: 10,
    category: 'Mala & Vilakku',
    description: 'Sesame seed wick lamp to dispel sorrow and negative planetary effects.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Karpoora Aarathi',
    amount: 50,
    category: 'Mala & Vilakku',
    description: 'Camphor deeparadhana offering.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Archanathattu (Devikku Thattu)',
    amount: 50,
    category: 'Mala & Vilakku',
    description: 'Plate of puja flowers, coconut, banana, and incense for archana.',
    source: 'keralapazhanitemple.com',
  },

  /* ── 7. Sanskaras & Life Events ── */
  {
    name: 'Choroonu (Anna Prasanam)',
    amount: 201,
    category: 'Sanskaras & Life Events',
    description: 'Child first solid food feeding ceremony before the deity with prasadam.',
    source: 'Both',
  },
  {
    name: 'Ezhuthiniruthal (Vidyarambham)',
    amount: 151,
    category: 'Sanskaras & Life Events',
    description: 'Initiation of children into learning by writing letters in raw rice.',
    source: 'Both',
  },
  {
    name: 'Mundanam (Motta / Thala Vettal)',
    amount: 453,
    category: 'Sanskaras & Life Events',
    description: 'Ceremonial head tonsuring sacrifice with vel samarpanam & abhishekam.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Noorum Paalum (for Nagas)',
    amount: 150,
    category: 'Sanskaras & Life Events',
    description: 'Turmeric powder, tender coconut, and milk offering for serpent deities.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Nagaroottu (Blessing of Rahu)',
    amount: 250,
    category: 'Sanskaras & Life Events',
    description: 'Feeding and propitiation ritual for Naga devatas to mitigate Sarpa dosham.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Charadu Japam',
    amount: 30,
    category: 'Sanskaras & Life Events',
    description: 'Chanting mantras over sacred sanctified protection thread.',
    source: 'templeofquilon.org',
  },
  {
    name: 'Murukanu Vel Samarpanam',
    amount: 101,
    category: 'Sanskaras & Life Events',
    description: 'Offering the sacred divine Spear (Vel) to Lord Subramanya.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Kavadiyenthi Pradhakshinam',
    amount: 101,
    category: 'Sanskaras & Life Events',
    description: 'Carrying decorated ritual Kavadi around the temple circumambulation.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Shashti Vritham',
    amount: 50,
    category: 'Sanskaras & Life Events',
    description: 'Special fasting archana performed on Skanda Shashti days.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Nel Para',
    amount: 151,
    category: 'Sanskaras & Life Events',
    description: 'Harvest grain (paddy) measuring vessel full offering to the Lord.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Vivaham (Temple Marriage)',
    amount: 2500,
    category: 'Sanskaras & Life Events',
    description: 'Standard temple wedding solemnization and blessings ceremony.',
    source: 'keralapazhanitemple.com',
  },
  {
    name: 'Vivaham (Special / Hall Marriage)',
    amount: 5000,
    category: 'Sanskaras & Life Events',
    description: 'Comprehensive wedding rituals with priest chanting and floral setup.',
    source: 'keralapazhanitemple.com',
  },
]
